apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  selector:
    app: test
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: default
type: Opaque
data:
  access-key: bWluaW9hZG1pbg==    # base64: minioadmin
  secret-key: bWluaW9hZG1pbjEyMw== # base64: minioadmin123
---
# RabbitMQ Secret
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: default
type: Opaque
data:
  username: cmFiYml0bXE=        # base64: rabbitmq
  password: cmFiYml0bXFwYXNz    # base64: rabbitmqpass

---
# Cassandra Secret
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-credentials
  namespace: default
type: Opaque
data:
  username: Y2Fzc2FuZHJh         # base64: cassandra
  password: Y2Fzc2FuZHJhcGFzcw== # base64: cassandrapass
            # base64: 9042
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: default
type: Opaque
data:
  password: cmVkaXNwYXNz  # base64: redispass
  host: cmVkaXMtc2VydmljZQ==  # base64: redis-service