apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  selector:
    app: test
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
# MinIO Secret
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: default
type: Opaque
data:
  access-key: bWluaW9hZG1pbg==    # base64: minioadmin
  secret-key: bWluaW9hZG1pbjEyMw== # base64: minioadmin123
  endpoint: aHR0cDovL21pbmlvOjkwMDA=  # base64: http://minio:9000
---
# RabbitMQ Secret
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: default
type: Opaque
data:
  username: cmFiYml0bXE=        # base64: rabbitmq
  password: cmFiYml0bXFwYXNz    # base64: rabbitmqpass
  host: cmFiYml0bXEtc2VydmljZQ== # base64: rabbitmq-service
  port: NTY3Mg==               # base64: 5672
---
# Cassandra Secret
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-credentials
  namespace: default
type: Opaque
data:
  username: Y2Fzc2FuZHJh         # base64: cassandra
  password: Y2Fzc2FuZHJhcGFzcw== # base64: cassandrapass
  hosts: Y2Fzc2FuZHJhLXNlcnZpY2U= # base64: cassandra-service
  port: OTA0Mg==               # base64: 9042