name: Build and Push Wire Utility Tool

on:
  push:
    branches:
      - main
    tags:
      - 'v*'      # Keep existing tag pattern for utility tool
    paths:
      - 'Dockerfile.utility'
      - 'scripts/entrypoint.py'
      - 'scripts/es-debug.py'
      - '.github/workflows/build-and-push.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile.utility'
      - 'scripts/entrypoint.py'
      - 'scripts/es-debug.py'
      - '.github/workflows/build-and-push.yml'

env:
  REGISTRY: quay.io
  IMAGE_NAME: wire/wire-utility-tool

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Skip if commit message contains [skip utility]
    if: "!contains(github.event.head_commit.message, '[skip utility]')"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.utility
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        run: |
          docker run --rm --platform linux/amd64 --entrypoint /bin/bash ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -c "
            echo 'Testing tools installation...' &&
            python3 --version &&
            python2 --version &&
            mc --version &&
            psql --version &&
            redis-cli --version &&
            cqlsh --version &&
            rabbitmqadmin --version &&
            echo 'All tools working correctly!'
          "
